# Makefile for EE450 hw0

# make main
# 	makes hw0 executable


main: HW0-extra-a.o
	g++ -o main -g -std=c++17 HW0-extra-a.o

HW0-extra-a.o: HW0-extra-a.cpp
	g++ -g -c -std=c++17 HW0-extra-a.cpp
