#!/usr/bin/python3

import os
import sys
import random
import base64
import unittest
import subprocess

TIMEOUT = 20

REF_SOLUTION = b'f0VMRgIBAQAAAAAAAAAAAAEAPgABAAAAAAAAAAAAAAAAAAAAAAAAAIBOAAAAAAAAAAAAAEAAAAAAAEAAJgAlAAEAAAALAAAAAQAAAAwAAAANAAAAAQAAABAAAAARAAAAEgAAAAEAAAAUAAAAFQAAAAEAAAAWAAAAFwAAAAEAAAAdAAAAHgAAAAAAAAAAAAAAQVVBVEGJ1VVTiftIg+xoi1YQSIt2GGRIiwQlKAAAAEiJRCRYMcDoAAAAAIP4/w+EjAEAAEiNNQAAAABIjT0AAAAAugkAAABMjSUAAAAA6AAAAABIiwUAAAAASItA6EmLrATwAAAASIXtD4STAQAAgH04AA+E1wAAAA++dUNIjT0AAAAA6AAAAABIicfoAAAAAEiNdCQQMcm6EAAAAInfSMdEJBgAAAAASMdEJCgAAAAASMdEJDgAAAAASMdEJEgAAAAARIlsJBDoAAAAAIP4EA+EOgEAAEiNNQAAAAC6GAAAAEiNPQAAAADoAAAAAEiLBQAAAABIi0DoSYucBPAAAABIhdsPhPgAAACAezgAdHgPvnNDSI09AAAAAOgAAAAASInH6AAAAAC4AQAAAEiLTCRYZEgzDCUoAAAAD4U9BwAASIPEaFtdQVxBXcMPH0AASInv6AAAAABIi0UASI0VAAAAAL4KAAAASItAMEg50A+ECP///0iJ7//QD77w6fv+//9mDx9EAABIid/oAAAAAEiLA0iNFQAAAAC+CgAAAEiLQDBIOdAPhGj///9Iid//0A++8Olb////Dx+AAAAAAInf6AAAAABIjTUAAAAASI09AAAAALobAAAA6AAAAABIiwUAAAAASI0VAAAAAEiLQOhIi5wC8AAAAEiF2w+FCP///+gAAAAAZg8fhAAAAAAASI01AAAAAEiNPQAAAAC6DQAAAOgAAAAASIsFAAAAAEiLQOhJi6wE8AAAAEiF7XTCgH04AA+EFgEAAA++dUNIjT0AAAAA6AAAAABIicfoAAAAAEiNdCQgMcm6EAAAAInf6AAAAACD+BC6FwAAAEiNNQAAAAAPhVj+//+LRCQQOUQkIA+EAAEAAEiNNQAAAABIjT0AAAAAuioAAADoAAAAAIt0JCBIjT0AAAAA6AAAAABIjTUAAAAASInHuhgAAABIicXoAAAAAIt0JBBIie/oAAAAAEmJxUiLAEiLQOhJi6wF8AAAAEiF7Q+EBP///4B9OAAPhDADAAAPvnVDTInv6AAAAABIicfoAAAAAGYPb0QkIEiNdCQwMcm6EAAAAInfDylEJDCDRCQwAegAAAAAg/gQD4SwAQAAuhYAAABIjTUAAAAA6Yn9//8PH4AAAAAASInv6AAAAABIi0UASI0VAAAAAL4KAAAASItAMEg50A+Eyf7//0iJ7//QD77w6bz+//9mDx9EAACLRCQkJf///wCD+Ap1eoB8JCcAdHNIg3wkKAC6HgAAAEiNNQAAAAB0DEiNNQAAAAC6CQAAAEiNPQAAAADoAAAAAEiLBQAAAABIi0DoSYusBPAAAABIhe0PhA3+//+AfTgAD4TaAwAAD751Q0iNPQAAAADoAAAAAEiJx+gAAAAA6QD///8PH0AASI01AAAAAEiNPQAAAAC6IgAAAOgAAAAAD7ZEJCRIjXQkD0iNPQAAAAC6AQAAAIhEJA/oAAAAAEiNNQAAAAC6AQAAAEiJx0iJxegAAAAAD7ZEJCVIjXQkDkiJ77oBAAAAiEQkDugAAAAASI01AAAAALoBAAAASInHSInF6AAAAAAPtkQkJkiNdCQNSInvugEAAACIRCQN6AAAAABIjTUAAAAAugEAAABIicdIicXoAAAAAA+2RCQnSI10JAy6AQAAAEiJ74hEJAzoAAAAAOnx/f//Zg8fRAAASI01AAAAAEiNPQAAAAC6CwAAAOgAAAAASIsFAAAAAEiLQOhJi6wE8AAAAEiF7Q+E1vz//4B9OAAPhMoAAAAPvnVDSI09AAAAAOgAAAAASInH6AAAAABIjXQkQDHJuhAAAACJ3+gAAAAAg/gQD4UGAQAAi0QkMDlEJEAPhRABAACLRCQ0OUQkRA+FjQEAAEiDfCRIALokAAAASI01AAAAAHQMSI01AAAAALoPAAAASI09AAAAAOgAAAAASIsFAAAAAEiLQOhJi5wE8AAAAEiF2w+ENPz//4B7OAAPhHACAAAPtkNDSI09AAAAAA++8OgAAAAASInH6AAAAAAxwOkz+///Zg8fRAAASInv6AAAAABIi0UASI0VAAAAAL4KAAAASItAMEg50A+EFf///0iJ7//QD77w6Qj///9mDx9EAABIie/oAAAAAEiLRQBIjRUAAAAAvgoAAABIi0AwSDnQD4Sv/P//SInv/9APvvDpovz//2YPH0QAALodAAAASI01AAAAAOlh+v//Dx+AAAAAAEiNNQAAAABIjT0AAAAAujAAAADoAAAAAIt0JEBIjT0AAAAA6AAAAABIjTUAAAAAuhgAAABIicdIicPoAAAAAIt0JDBIid/oAAAAAEiJxUiLAEiLQOhIi5wF8AAAAEiF2w+EFPv//4B7OAAPhBgBAAAPvnNDSInv6AAAAABIicfoAAAAADHA6Rr6//9IjTUAAAAASI09AAAAALouAAAA6AAAAAAPtnQkREiNPQAAAADoAAAAAEiNNQAAAAC6AQAAAEiJx0iJw+gAAAAAD7Z0JEVIid/oAAAAAEiNNQAAAAC6AQAAAEiJx0iJw+gAAAAAD7Z0JEZIid/oAAAAAEiNNQAAAAC6AQAAAEiJx0iJw+gAAAAAD7Z0JEdIid/oAAAAAEiJxUiLAEiLQOhIi5wF8AAAAEiF2w+EP/r//4B7OAAPhJYAAAAPtkNDD77w6SP///9Iie/oAAAAAEiLRQBIjRUAAAAAvgoAAABIi0AwSDnQD4QF/P//SInv/9APvvDp+Pv//w8fRAAASInf6AAAAABIiwNIjRUAAAAAvgoAAABIi0AwSDnQD4TI/v//SInf/9APvvDpu/7//w8fgAAAAABIid/oAAAAAEiLA74KAAAASInf/1Aw6Xn9//9Iid/oAAAAAEiLA74KAAAASInf/1Aw6VP////oAAAAAA8fAGYuDx+EAAAAAABBVkFVQbgEAAAAQVRVTGPiU0iJ9boCAAAAvgEAAACJ+0iB7PAAAABIjUwkCMdEJAgBAAAAZEiLBCUoAAAASImEJOgAAAAxwOgAAAAAi1UQSIt1GInf6AAAAACD+P8PhF0BAAC+BQAAAInf6AAAAACD+P+6EAAAAEiNNQAAAAAPhE8BAABIjVQkDEiNdCRgid/HRCQMgAAAAOgAAAAAg/j/icO6EAAAAEiNNQAAAAAPhB8BAABIjTUAAAAASI09AAAAALoIAAAATI0tAAAAAOgAAAAASIsFAAAAAEiLQOhJi6wF8AAAAEiF7Q+ElAIAAIB9OAAPhJcCAAAPvnVDSI09AAAAAOgAAAAASInH6AAAAABIjXQkIDHJuhAAAACJ30jHRCQoAAAAAEjHRCQ4AAAAAEjHRCRIAAAAAEjHRCRYAAAAAOgAAAAASIP4EEiJxQ+EYwEAAEiNNQAAAABIjT0AAAAAuhwAAADoAAAAAEiNPQAAAABIie7oAAAAAEiJxUiLAEiLQOhIi5wF8AAAAEiF2w+E7AEAAIB7OAAPhN8AAAAPvnNDSInv6AAAAABIicfoAAAAALgBAAAA62kPH0AAid/oAAAAAEiNNQAAAAC6DgAAAEiNPQAAAADoAAAAAEiLBQAAAABIjRUAAAAASItA6EiLnALwAAAASIXbD4SBAQAAgHs4AHRID75zQ0iNPQAAAADoAAAAAEiJx+gAAAAAuAEAAABIi4wk6AAAAGRIMwwlKAAAAA+F9AUAAEiBxPAAAABbXUFcQV1BXsMPH0AASInf6AAAAABIiwNIjRUAAAAAvgoAAABIi0AwSDnQdJxIid//0A++8OuSZg8fRAAASInf6AAAAABIiwNIjRUAAAAAvgoAAABIi0AwSDnQD4QB////SInf/9APvvDp9P7//w8fgAAAAABIjTUAAAAASI09AAAAALoNAAAA6AAAAABIiwUAAAAASItA6EmLrAXwAAAASIXtD4SXAAAAgH04AA+EkgIAAA++dUNIjT0AAAAA6AAAAABIicfoAAAAAGYPb0QkILgKAAAADylEJDBmiUQkNMZEJDYARIhkJDfoAAAAAEiNdCQwMcm6EAAAAInfSIlEJDjoAAAAAIP4EHR5SI01AAAAALoUAAAASI09AAAAAOgAAAAASIsFAAAAAEiLQOhJi5wF8AAAAEiF2w+Ff/7//+gAAAAADx+EAAAAAABIie/oAAAAAEiLRQBIjRUAAAAAvgoAAABIi0AwSDnQD4RI/f//SInv/9APvvDpO/3//2YPH0QAAEiNNQAAAABIjT0AAAAAugkAAADoAAAAAEiLBQAAAABIi0DoSYusBfAAAABIhe10i4B9OAAPhL4BAAAPvnVDSI09AAAAAOgAAAAASInH6AAAAABIjXQkQDHJuhAAAACJ3+gAAAAASIP4ELoZAAAASI01AAAAAA+FGP///4tEJDCDwAE5RCRAD4SkAQAASI01AAAAAEiNPQAAAAC6LAAAAOgAAAAAi3QkQEiNPQAAAADoAAAAAEiNNQAAAAC6GAAAAEiJx0iJxegAAAAAi0QkMEiJ741wAegAAAAASYnGSIsASItA6EmLrAbwAAAASIXtD4TG/v//gH04AA+EaQIAAA++dUNMiffoAAAAAEiJx+gAAAAATYXkfmJMieBIus/3U+Olm8QgSI1sJBBI9+pIidBMieJIwfgHSMH6P0gp0EiJRCQQSGnA6AMAAEkpxElpxEBCDwBIiUQkGOsPDx9EAADoAAAAAIM4BHUQSInuSInv6AAAAACD+P905mYPb0QkQA8pRCRQ6AAAAABIjXQkUDHJuhAAAACJ30iJRCRY6AAAAACD+BAPhFkBAAC6GgAAAEiNNQAAAADp1/3//w8fQABIie/oAAAAAEiLRQBIjRUAAAAAvgoAAABIi0AwSDnQD4RN/f//SInv/9APvvDpQP3//2YPH0QAAEiJ7+gAAAAASItFAEiNFQAAAAC+CgAAAEiLQDBIOdAPhCH+//9Iie//0A++8OkU/v//Zg8fRAAAi0QkNDlEJEQPhGIBAABIjTUAAAAASI09AAAAALoqAAAA6AAAAAAPtnQkREiNPQAAAADoAAAAAEiNNQAAAAC6AQAAAEiJx0iJxegAAAAAD7Z0JEVIie/oAAAAAEiNNQAAAAC6AQAAAEiJx0iJxegAAAAAD7Z0JEZIie/oAAAAAEiNNQAAAAC6AQAAAEiJx0iJxegAAAAAD7Z0JEdIie/oAAAAAEmJxkiLAEiLQOhJi6wG8AAAAEiF7Q+Ezfz//4B9OAAPhDgBAAAPtkVDD77w6f/9//9IjTUAAAAASI09AAAAALoPAAAA6AAAAABIiwUAAAAASItA6EmLrAXwAAAASIXtD4SD/P//gH04AA+EuAAAAA++dUNIjT0AAAAA6AAAAABIicfoAAAAAInf6AAAAAAxwOn1+v//SInv6AAAAABIi0UASI0VAAAAAL4KAAAASItAMEg50A+Edv3//0iJ7//QD77w6Wn9//9mDx9EAABIjTUAAAAASI09AAAAALoLAAAA6AAAAABIiwUAAAAASItA6EmLrAXwAAAASIXtD4Tn+///gH04AHRyD7ZFQ0iNPQAAAAAPvvDoAAAAAEiJx+gAAAAA6Rn9//9Iie/oAAAAAEiLRQBIjRUAAAAAvgoAAABIi0AwSDnQD4Qn////SInv/9APvvDpGv///w8fQABIie/oAAAAAEiLRQC+CgAAAEiJ7/9QMOmw/v//SInv6AAAAABIi0UAvgoAAABIie//UDDpdv///+gAAAAAAAAAAAAAAAAAAACJ8MMAAAAAAAAAAAAAAAAA6QAAAABGYWlsZWQgdG8gY29ubmVjdCB0byBzZXJ2ZXIAQ09OTkVDVEVEAEZhaWxlZCB0byBzZW5kIERJU0NPVkVSWQBESVNDT1ZFUlk6IE9LAEZhaWxlZCB0byByZWNlaXZlIE9GRkVSACByZWNlaXZlZCBidXQgZXhwZWN0aW5nIAAuAE9GRkVSOiBPSwBGYWlsZWQgdG8gc2VuZCBSRVFVRVNUAFJFUVVFU1Q6IE9LAEZhaWxlZCB0byByZWNlaXZlIEFDS05PV0xFREdFAEFDS05PV0xFREdFOiBPSwBGYWlsZWQgdG8gYmluZABGYWlsZWQgdG8gbGlzdGVuAEZhaWxlZCB0byBhY2NlcHQAQUNDRVBURUQARmFpbGVkIHRvIHJlY2VpdmUgRElTQ09WRVJZIABGYWlsZWQgdG8gc2VuZCBPRkZFUgBGYWlsZWQgdG8gcmVjZWl2ZSBSRVFVRVNUAEZhaWxlZCB0byBzZW5kIEFDS05PV0xFREdFADg4ODgAZ2V0YWRkcmluZm86IABzb2NrZXQ6IGNyZWF0aW9uAGNsaWVudABzdG9pAHNlcnZlcgBydW4gYXM6IGxhYjIgW2NsaWVudHxzZXJ2ZXJdAAAAAE9GRkVSOiByZWNlaXZlZCBkaWZmZXJlbnQgdHJhbnNhY3Rpb25faWQsIAAAAAAAAE9GRkVSOiByZWNlaXZlZCBpcCBvdXRzaWRlIHJhbmdlLCAAAAAAAABPRkZFUjogcmVjZWl2ZWQgdGltZXN0YW1wIGlzIDAAAEFDS05PV0xFREdFOiByZWNlaXZlZCBkaWZmZXJlbnQgdHJhbnNhY3Rpb25faWQsIAAAAAAAAAAAQUNLTk9XTEVER0U6IHJlY2VpdmVkIGlwIGRpZmZlcmVuIGZyb20gb2ZmZXIsIAAAQUNLTk9XTEVER0U6IHJlY2VpdmVkIHRpbWVzdGFtcCBpcyAwAAAAAFJFUVVFU1Q6IHJlY2VpdmVkIGRpZmZlcmVudCB0cmFuc2FjdGlvbl9pZCwgAAAAAFJFUVVFU1Q6IHJlY2VpdmVkIGlwIGRpZmZlcmVuIGZyb20gb2ZmZXIsIAAAAAAAAEFXQVZJif9BVUFUSYn2VVNIidVJicxIg+woRIlEJAxkSIsEJSgAAABIiUQkGDHA6AAAAABEi0QkDESLKEiJw8cAAAAAAEiNdCQQSInvRInCQf/XSItUJBBIOep0Y4szg/4idES5AAAAgL//////SAHBSDn5dzJNheR0B0gp6kmJFCSF9nUDRIkrSIt8JBhkSDM8JSgAAAB1L0iDxChbXUFcQV1BXkFfw0yJ9+gAAAAAgzsAdQNEiStIicfoAAAAAEyJ9+gAAAAA6AAAAAD//wEQUGCwAQC7AQUAAMMBBbABAAAAAAAAAABiYXNpY19zdHJpbmc6Ol9NX2NvbnN0cnVjdCBudWxsIG5vdCB2YWxpZAAAAAAAAAAAAAAAAAAAAEFVQVRMjWcQVVNIg+wISIX2TIkndHJIif1IifdJifXoAAAAAEiD+A9IicN3M0iD+AF0HUiFwHU8SIldCEHGBBwASIPECFtdQVxBXcMPH0AAQQ+2RQCIRRDr3mYPH0QAAEiNeAHoAAAAAEiJXRBJicRIiUUATInnSInaTInu6AAAAABMi2UA67BIjT0AAAAA6AAAAAAAAAAAAAAAAAAAAABBVUFUSYn8VVNJifVIg+wISItfCEiJ9+gAAAAASInCSInFSDnDSA9G00iF0nQiSYs8JEyJ7ugAAAAAhcB0EkiDxAhbXUFcQV3DDx+AAAAAAEgp67j///9/SIH7////f3/djUABSIH7AAAAgA9Nw0iDxAhbXUFcQV3DAAAAAAAAAEFXQVZBVUFUSYn0VVNIjTUAAAAAZg/vwIn9SIHsqAAAADH/SI1UJCBIjUwkGMdEJCABAAAADxFEJCRIx0IkAAAAAMdCLAAAAAAPEUIUZEiLBCUoAAAASImEJJgAAAAxwMdEJCgBAAAA6AAAAACFwInDD4XsAAAASItEJBiLUAyLcAiLeAToAAAAAIP4/0GJxg+EFAEAAIP9AQ+OQwEAAEmLdCQITI1sJFBMjXwkF0yJ70yJ+ugAAAAASI01AAAAAEyJ7+gAAAAAhcB1HYP9Arp7AAAAD4WWAQAASIt0JBhEiffoAAAAAInDSI01AAAAAEyJ7+gAAAAAhcB1HYP9Arp7AAAAD4ULAQAASIt0JBhEiffoAAAAAInDRIn36AAAAABIi3wkUEmDxRBMOe90CegAAAAADx9AAEiLjCSYAAAAZEgzDCUoAAAAidgPhXoBAABIgcSoAAAAW11BXEFdQV5BX8NIjT0AAAAA6AAAAABIjTUAAAAASI09AAAAAEiJwugAAAAAid+7AQAAAOgAAAAASI09AAAAAEiJxugAAAAASInH6AAAAADrjkiNPQAAAAC7AQAAAOgAAAAASI01AAAAAEiNPQAAAABIicLoAAAAAEiNPQAAAADoAAAAAOlW////SI09AAAAAOgAAAAASI01AAAAAEiNPQAAAABIicLoAAAAAEiNPQAAAADoAAAAAOkj////SI1cJHBJi3QkEEyJ+kiJ3+gAAAAASItUJHBIiz0AAAAASI01AAAAAEG4CgAAADHJ6AAAAABIi3wkcEiDwxCJwkg53w+ErP7//4lEJAzoAAAAAItUJAzpmv7//0iNXCRwSYt0JBBMifpIid/oAAAAAEiLVCRwSIs9AAAAAEiNNQAAAABBuAoAAAAxyegAAAAASIt8JHBIg8MQicJIOd8PhCH+//+JRCQM6AAAAACLVCQM6Q/+///oAAAAAEiLfCRwSIPDEEiJxUg533QF6AAAAABIi3wkUEmDxRBMOe90BegAAAAASInv6AAAAADrzUiJxeveDx+EAAAAAABIjT0AAAAASIPsCOgAAAAASIs9AAAAAEiNFQAAAABIjTUAAAAASIPECOkAAAAA//8BLWhRAADiAT+DBgCAA5ABAAClBAWDBgDFBAWBBgCABQWDBgCgBQXQBQD8BQUAAAAAAAAAAAAAAAAAAAAAAAAAAEdDQzogKFVidW50dSA3LjUuMC0zdWJ1bnR1MX4xOC4wNCkgNy41LjAAAAAAAAAAFAAAAAAAAAABelIAAXgQARsMBwiQAQAAEAAAABwAAAAAAAAAAwAAAAAAAAAQAAAAMAAAAAAAAAAFAAAAAAAAADwAAABEAAAAAAAAAIMIAAAAQg4QjQJCDhiMA0QOIIYEQQ4ogwVGDpABAzYBCg4oQQ4gQQ4YQg4QQg4IRQsAAABEAAAAhAAAAAAAAAA1CAAAAEIOEI4CQg4YjQNIDiCMBEEOKIYFRA4wgwZWDqACAxwCCg4wQQ4oQQ4gQg4YQg4QQg4IRQsAAAAcAAAAAAAAAAF6UExSAAF4EAebAAAAABsbDAcIkAEAAEwAAAAkAAAAAAAAAM0AAAAEAAAAAEIOEI8CQg4YjgNFDiCNBEIOKIwFRA4whgZBDjiDB0oOYAKDCg44QQ4wQQ4oQg4gQg4YQg4QQg4IQQsAOAAAADwBAAAAAAAAlAAAAABCDhCNAkIOGIwDRQ4ghgRBDiiDBUQOMHcKDihBDiBBDhhCDhBCDghFCwAASAAAAHgBAAAAAAAAeQAAAABCDhCNAkIOGIwDRA4ghgRBDiiDBUcOMHIKDihBDiBBDhhCDhBCDghIC2IOKEEOIEEOGEIOEEIOCAAAAFAAAAD8AAAAAAAAAAgDAAAEAAAAAEIOEI8CQg4YjgNCDiCNBEIOKIwFRA4whgZBDjiDB1QO4AEDNwEKDjhBDjBBDihCDiBCDhhCDhBCDghBCwAAABgAAAAYAgAAAAAAAC4AAAAASw4QXg4IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAAAAAAAwAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAaAAAAAAAAAAAAAAAAAAAAAAAKAAAAAgAYABADAAAAAAAALgAAAAAAAAAvAAAAAQAKAAAAAAAAAAAAAQAAAAAAAAAAAAAAAwAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAhAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAOABwAAAAAAAAAAAAAAAAAAABDAAAAAAAOACYAAAAAAAAAAAAAAAAAAABIAAAAAAAOAAAAAAAAAAAAAAAAAAAAAABNAAAAAAAOAD8AAAAAAAAAAAAAAAAAAABSAAAAAAAOAE0AAAAAAAAAAAAAAAAAAABXAAAAAAAPAAAAAAAAAAAAAAAAAAAAAABcAAAAAAAOAGUAAAAAAAAAAAAAAAAAAABhAAAAAAAOAIoAAAAAAAAAAAAAAAAAAABnAAAAAAAPAFgAAAAAAAAAAAAAAAAAAABsAAAAAAAOAIAAAAAAAAAAAAAAAAAAAAByAAAAAAAPADAAAAAAAAAAAAAAAAAAAAB3AAAAAAAOAH4AAAAAAAAAAAAAAAAAAAB8AAAAAAAOAKEAAAAAAAAAAAAAAAAAAACCAAAAAAAPAOAAAAAAAAAAAAAAAAAAAACIAAAAAAAOAMsAAAAAAAAAAAAAAAAAAACOAAAAAAAOAK0AAAAAAAAAAAAAAAAAAACUAAAAAAAPAHgAAAAAAAAAAAAAAAAAAACaAAAAAAAPALAAAAAAAAAAAAAAAAAAAACgAAAAAAAOAOoAAAAAAAAAAAAAAAAAAACmAAAAAAAOAPsAAAAAAAAAAAAAAAAAAACsAAAAAAAOAAwBAAAAAAAAAAAAAAAAAACyAAAAAAAOABUBAAAAAAAAAAAAAAAAAAC4AAAAAAAOANsAAAAAAAAAAAAAAAAAAAC+AAAAAAAOADIBAAAAAAAAAAAAAAAAAADEAAAAAAAOAEcBAAAAAAAAAAAAAAAAAADKAAAAAAAPAAgBAAAAAAAAAAAAAAAAAADQAAAAAAAOAGEBAAAAAAAAAAAAAAAAAADWAAAAAAAPADgBAAAAAAAAAAAAAAAAAADcAAAAAAATAAAAAAAAAAAAAAAAAAAAAADiAAAAAAAOAHwBAAAAAAAAAAAAAAAAAADoAAAAAAAOAKABAAAAAAAAAAAAAAAAAADuAAAAAAAOAKwBAAAAAAAAAAAAAAAAAAD0AAAAAAAOAIEBAAAAAAAAAAAAAAAAAAD6AAAAAAAOAI8BAAAAAAAAAAAAAAAAAAAAAQAAAAAOALMBAAAAAAAAAAAAAAAAAAAGAQAAAAAOAKcBAAAAAAAAAAAAAAAAAAAMAQAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAGAAAAAAAAAAAAAAAAAAAAAABNAQAAIgALAAAAAAAAAAAAAwAAAAAAAABoAQAAIgAMAAAAAAAAAAAABQAAAAAAAACJAQAAEAAAAAAAAAAAAAAAAAAAAAAAAACfAQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAEgAHAAAAAAAAAAAAgwgAAAAAAACmAQAAEAAAAAAAAAAAAAAAAAAAAAAAAACuAQAAEAAAAAAAAAAAAAAAAAAAAAAAAAC4AQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAGAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAASAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAAlAgAAEAAAAAAAAAAAAAAAAAAAAAAAAABGAgAAEAAAAAAAAAAAAAAAAAAAAAAAAABMAgAAEAAAAAAAAAAAAAAAAAAAAAAAAABkAgAAEAAAAAAAAAAAAAAAAAAAAAAAAABpAgAAEAAAAAAAAAAAAAAAAAAAAAAAAABzAgAAEAAAAAAAAAAAAAAAAAAAAAAAAACEAgAAEgAHAJAIAAAAAAAANQgAAAAAAACaAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAClAgAAEAAAAAAAAAAAAAAAAAAAAAAAAACqAgAAEAAAAAAAAAAAAAAAAAAAAAAAAACxAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAC4AgAAEAAAAAAAAAAAAAAAAAAAAAAAAADRAgAAEAAAAAAAAAAAAAAAAAAAAAAAAAD2AgAAEAAAAAAAAAAAAAAAAAAAAAAAAAAHAwAAEAAAAAAAAAAAAAAAAAAAAAAAAAARAwAAIgAQAAAAAAAAAAAAzQAAAAAAAABRAwAAIQIdAAAAAAAAAAAACAAAAAAAAABtAwAAEAAAAAAAAAAAAAAAAAAAAAAAAACLAwAAEAAAAAAAAAAAAAAAAAAAAAAAAACaAwAAEAAAAAAAAAAAAAAAAAAAAAAAAABYAwAAEAAAAAAAAAAAAAAAAAAAAAAAAAC8AwAAIgAUAAAAAAAAAAAAlAAAAAAAAAD9AwAAEAAAAAAAAAAAAAAAAAAAAAAAAAADBAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAKBAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAnBAAAIgAUAAAAAAAAAAAAlAAAAAAAAABoBAAAIgAWAAAAAAAAAAAAeQAAAAAAAACrBAAAEAAAAAAAAAAAAAAAAAAAAAAAAACyBAAAEgAYAAAAAAAAAAAACAMAAAAAAAC3BAAAEAAAAAAAAAAAAAAAAAAAAAAAAADDBAAAEAAAAAAAAAAAAAAAAAAAAAAAAADKBAAAEAAAAAAAAAAAAAAAAAAAAAAAAADRBAAAEAAAAAAAAAAAAAAAAAAAAAAAAADbBAAAEAAAAAAAAAAAAAAAAAAAAAAAAADoBAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgBQAAEAAAAAAAAAAAAAAAAAAAAAAAAABbBQAAEAAAAAAAAAAAAAAAAAAAAAAAAABiBQAAEAAAAAAAAAAAAAAAAAAAAAAAAAB6BQAAEAAAAAAAAAAAAAAAAAAAAAAAAACSBQAAEAIAAAAAAAAAAAAAAAAAAAAAAACfBQAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAbGFiMi5jcHAAX0dMT0JBTF9fc3ViX0lfX1o2Y2xpZW50aVA4YWRkcmluZm9pAF9aU3RMOF9faW9pbml0AC5MQzEALkxDMgAuTEMwAC5MQzMALkxDNAAuTEM1AC5MQzYALkxDMTEALkxDOQAuTEMxMAAuTEM3AC5MQzgALkxDMTIALkxDMTYALkxDMTcALkxDMTMALkxDMTQALkxDMTUALkxDMTkALkxDMjAALkxDMjEALkxDMjIALkxDMTgALkxDMjMALkxDMjQALkxDMjUALkxDMjcALkxDMjYALkxDMjgALkxDMjkALkxDMzIALkxDMzQALkxDMzAALkxDMzEALkxDMzUALkxDMzMAX1pOU3Q3X19jeHgxMTEyYmFzaWNfc3RyaW5nSWNTdDExY2hhcl90cmFpdHNJY0VTYUljRUVDNUVQS2NSS1MzXwBfWk5LU3Q1Y3R5cGVJY0U4ZG9fd2lkZW5FYwBfWk5TdDExY2hhcl90cmFpdHNJY0U2bGVuZ3RoRVBLYwBfR0xPQkFMX09GRlNFVF9UQUJMRV8Ac3RybGVuAGNvbm5lY3QAX1pTdDRjb3V0AF9aU3QxNl9fb3N0cmVhbV9pbnNlcnRJY1N0MTFjaGFyX3RyYWl0c0ljRUVSU3QxM2Jhc2ljX29zdHJlYW1JVF9UMF9FUzZfUEtTM19sAF9aTlNvM3B1dEVjAF9aTlNvNWZsdXNoRXYAc2VuZABfWk5LU3Q1Y3R5cGVJY0UxM19NX3dpZGVuX2luaXRFdgBjbG9zZQBfWlN0MTZfX3Rocm93X2JhZF9jYXN0dgByZWN2AF9aTlNvbHNFaQBfX3N0YWNrX2Noa19mYWlsAF9aNnNlcnZlcmlQOGFkZHJpbmZvaQBzZXRzb2Nrb3B0AGJpbmQAbGlzdGVuAGFjY2VwdABfWk5TbzlfTV9pbnNlcnRJbEVFUlNvVF8AX1pOU3Q2Y2hyb25vM19WMjEyc3RlYWR5X2Nsb2NrM25vd0V2AF9fZXJybm9fbG9jYXRpb24AbmFub3NsZWVwAF9aTjlfX2dudV9jeHg2X19zdG9hSWxpY0ppRUVFVDBfUEZUX1BLVDFfUFBTM19EcFQyX0VQS2NTNV9QbVM5XwBEVy5yZWYuX19neHhfcGVyc29uYWxpdHlfdjAAX1pTdDIwX190aHJvd19vdXRfb2ZfcmFuZ2VQS2MAX1Vud2luZF9SZXN1bWUAX1pTdDI0X190aHJvd19pbnZhbGlkX2FyZ3VtZW50UEtjAF9aTlN0N19fY3h4MTExMmJhc2ljX3N0cmluZ0ljU3QxMWNoYXJfdHJhaXRzSWNFU2FJY0VFQzJFUEtjUktTM18AX1pud20AbWVtY3B5AF9aU3QxOV9fdGhyb3dfbG9naWNfZXJyb3JQS2MAX1pOU3Q3X19jeHgxMTEyYmFzaWNfc3RyaW5nSWNTdDExY2hhcl90cmFpdHNJY0VTYUljRUVDMUVQS2NSS1MzXwBfWk5LU3Q3X19jeHgxMTEyYmFzaWNfc3RyaW5nSWNTdDExY2hhcl90cmFpdHNJY0VTYUljRUU3Y29tcGFyZUVQS2MAbWVtY21wAG1haW4AZ2V0YWRkcmluZm8Ac29ja2V0AF9aZGxQdgBfWlN0NGNlcnIAZ2FpX3N0cmVycm9yAF9aU3Rsc0lTdDExY2hhcl90cmFpdHNJY0VFUlN0MTNiYXNpY19vc3RyZWFtSWNUX0VTNV9QS2MAX1pTdDRlbmRsSWNTdDExY2hhcl90cmFpdHNJY0VFUlN0MTNiYXNpY19vc3RyZWFtSVRfVDBfRVM2XwBzdHJ0b2wAX1pOU3Q4aW9zX2Jhc2U0SW5pdEMxRXYAX1pOU3Q4aW9zX2Jhc2U0SW5pdEQxRXYAX19kc29faGFuZGxlAF9fY3hhX2F0ZXhpdAAAAAAAJwAAAAAAAAAEAAAARwAAAPz/////////NwAAAAAAAAACAAAAFgAAAPz/////////PgAAAAAAAAACAAAASAAAAPz/////////SgAAAAAAAAACAAAASAAAAPz/////////TwAAAAAAAAAEAAAASQAAAPz/////////VgAAAAAAAAACAAAASAAAAPz/////////gAAAAAAAAAACAAAASAAAAPz/////////hQAAAAAAAAAEAAAASgAAAPz/////////jQAAAAAAAAAEAAAASwAAAPz/////////yQAAAAAAAAAEAAAATAAAAPz/////////2QAAAAAAAAACAAAAFwAAAPz/////////5QAAAAAAAAACAAAASAAAAPz/////////6gAAAAAAAAAEAAAASQAAAPz/////////8QAAAAAAAAACAAAASAAAAPz/////////FwEAAAAAAAACAAAASAAAAPz/////////HAEAAAAAAAAEAAAASgAAAPz/////////JAEAAAAAAAAEAAAASwAAAPz/////////VAEAAAAAAAAEAAAATQAAAPz/////////XwEAAAAAAAACAAAAQgAAAPz/////////jAEAAAAAAAAEAAAATQAAAPz/////////lgEAAAAAAAACAAAAQgAAAPz/////////wwEAAAAAAAAEAAAATgAAAPz/////////ygEAAAAAAAACAAAAGAAAAPz/////////0QEAAAAAAAACAAAASAAAAPz/////////2wEAAAAAAAAEAAAASQAAAPz/////////4gEAAAAAAAACAAAASAAAAPz/////////6QEAAAAAAAACAAAASAAAAPz/////////AwIAAAAAAAAEAAAATwAAAPz/////////EwIAAAAAAAACAAAAGQAAAPz/////////GgIAAAAAAAACAAAASAAAAPz/////////JAIAAAAAAAAEAAAASQAAAPz/////////KwIAAAAAAAACAAAASAAAAPz/////////UQIAAAAAAAACAAAASAAAAPz/////////VgIAAAAAAAAEAAAASgAAAPz/////////XgIAAAAAAAAEAAAASwAAAPz/////////cQIAAAAAAAAEAAAAUAAAAPz/////////gAIAAAAAAAACAAAAGgAAAPz/////////mwIAAAAAAAACAAAAGwAAAPz/////////ogIAAAAAAAACAAAASAAAAPz/////////rAIAAAAAAAAEAAAASQAAAPz/////////twIAAAAAAAACAAAASAAAAPz/////////vAIAAAAAAAAEAAAAUQAAAPz/////////wwIAAAAAAAACAAAAHAAAAPz/////////0wIAAAAAAAAEAAAASQAAAPz/////////3wIAAAAAAAAEAAAAUQAAAPz/////////EAMAAAAAAAAEAAAASgAAAPz/////////GAMAAAAAAAAEAAAASwAAAPz/////////OwMAAAAAAAAEAAAATAAAAPz/////////UAMAAAAAAAACAAAAHQAAAPz/////////ZAMAAAAAAAAEAAAATQAAAPz/////////bwMAAAAAAAACAAAAQgAAAPz/////////uwMAAAAAAAACAAAAHgAAAPz/////////xAMAAAAAAAACAAAAHwAAAPz/////////0AMAAAAAAAACAAAASAAAAPz/////////1QMAAAAAAAAEAAAASQAAAPz/////////3AMAAAAAAAACAAAASAAAAPz/////////BgQAAAAAAAACAAAASAAAAPz/////////CwQAAAAAAAAEAAAASgAAAPz/////////EwQAAAAAAAAEAAAASwAAAPz/////////IwQAAAAAAAACAAAAIAAAAPz/////////KgQAAAAAAAACAAAASAAAAPz/////////NAQAAAAAAAAEAAAASQAAAPz/////////RQQAAAAAAAACAAAASAAAAPz/////////UwQAAAAAAAAEAAAASQAAAPz/////////WgQAAAAAAAACAAAAIQAAAPz/////////agQAAAAAAAAEAAAASQAAAPz/////////hQQAAAAAAAAEAAAASQAAAPz/////////jAQAAAAAAAACAAAAIQAAAPz/////////nAQAAAAAAAAEAAAASQAAAPz/////////twQAAAAAAAAEAAAASQAAAPz/////////vgQAAAAAAAACAAAAIQAAAPz/////////zgQAAAAAAAAEAAAASQAAAPz/////////6QQAAAAAAAAEAAAASQAAAPz/////////+wQAAAAAAAACAAAAIgAAAPz/////////AgUAAAAAAAACAAAASAAAAPz/////////DAUAAAAAAAAEAAAASQAAAPz/////////EwUAAAAAAAACAAAASAAAAPz/////////PQUAAAAAAAACAAAASAAAAPz/////////QgUAAAAAAAAEAAAASgAAAPz/////////SgUAAAAAAAAEAAAASwAAAPz/////////XQUAAAAAAAAEAAAAUAAAAPz/////////lAUAAAAAAAACAAAAIwAAAPz/////////nQUAAAAAAAACAAAAJAAAAPz/////////qQUAAAAAAAACAAAASAAAAPz/////////rgUAAAAAAAAEAAAASQAAAPz/////////tQUAAAAAAAACAAAASAAAAPz/////////3wUAAAAAAAACAAAASAAAAPz/////////5wUAAAAAAAAEAAAASgAAAPz/////////7wUAAAAAAAAEAAAASwAAAPz/////////BAYAAAAAAAAEAAAATQAAAPz/////////DwYAAAAAAAACAAAAQgAAAPz/////////PAYAAAAAAAAEAAAATQAAAPz/////////RwYAAAAAAAACAAAAQgAAAPz/////////eAYAAAAAAAACAAAAJQAAAPz/////////iwYAAAAAAAACAAAAJgAAAPz/////////kgYAAAAAAAACAAAASAAAAPz/////////nAYAAAAAAAAEAAAASQAAAPz/////////pwYAAAAAAAACAAAASAAAAPz/////////rAYAAAAAAAAEAAAAUQAAAPz/////////swYAAAAAAAACAAAAHAAAAPz/////////wwYAAAAAAAAEAAAASQAAAPz/////////zwYAAAAAAAAEAAAAUQAAAPz/////////AAcAAAAAAAAEAAAASgAAAPz/////////CAcAAAAAAAAEAAAASwAAAPz/////////FgcAAAAAAAACAAAAJwAAAPz/////////HQcAAAAAAAACAAAASAAAAPz/////////JwcAAAAAAAAEAAAASQAAAPz/////////MwcAAAAAAAACAAAASAAAAPz/////////OAcAAAAAAAAEAAAAUQAAAPz/////////PwcAAAAAAAACAAAAIQAAAPz/////////TwcAAAAAAAAEAAAASQAAAPz/////////XAcAAAAAAAAEAAAAUQAAAPz/////////YwcAAAAAAAACAAAAIQAAAPz/////////cwcAAAAAAAAEAAAASQAAAPz/////////gAcAAAAAAAAEAAAAUQAAAPz/////////hwcAAAAAAAACAAAAIQAAAPz/////////lwcAAAAAAAAEAAAASQAAAPz/////////pAcAAAAAAAAEAAAAUQAAAPz/////////3QcAAAAAAAAEAAAATQAAAPz/////////6AcAAAAAAAACAAAAQgAAAPz/////////FAgAAAAAAAAEAAAATQAAAPz/////////HggAAAAAAAACAAAAQgAAAPz/////////TAgAAAAAAAAEAAAATQAAAPz/////////ZwgAAAAAAAAEAAAATQAAAPz/////////fwgAAAAAAAAEAAAAUgAAAPz/////////2AgAAAAAAAAEAAAAVAAAAPz/////////5ggAAAAAAAAEAAAAVQAAAPz/////////+wgAAAAAAAAEAAAAVgAAAPz/////////CgkAAAAAAAACAAAAKAAAAPz/////////KQkAAAAAAAAEAAAAVwAAAPz/////////OgkAAAAAAAACAAAAKQAAAPz/////////RwkAAAAAAAACAAAAKgAAAPz/////////TgkAAAAAAAACAAAASAAAAPz/////////WgkAAAAAAAACAAAASAAAAPz/////////XwkAAAAAAAAEAAAASQAAAPz/////////ZgkAAAAAAAACAAAASAAAAPz/////////kAkAAAAAAAACAAAASAAAAPz/////////lQkAAAAAAAAEAAAASgAAAPz/////////nQkAAAAAAAAEAAAASwAAAPz/////////1AkAAAAAAAAEAAAAUAAAAPz/////////6AkAAAAAAAACAAAAKwAAAPz/////////7wkAAAAAAAACAAAASAAAAPz/////////+QkAAAAAAAAEAAAASQAAAPz/////////AAoAAAAAAAACAAAASAAAAPz/////////CAoAAAAAAAAEAAAAWAAAAPz/////////OQoAAAAAAAAEAAAASgAAAPz/////////QQoAAAAAAAAEAAAASwAAAPz/////////UwoAAAAAAAAEAAAATgAAAPz/////////WgoAAAAAAAACAAAALAAAAPz/////////ZgoAAAAAAAACAAAASAAAAPz/////////awoAAAAAAAAEAAAASQAAAPz/////////cgoAAAAAAAACAAAASAAAAPz/////////eQoAAAAAAAACAAAASAAAAPz/////////nwoAAAAAAAACAAAASAAAAPz/////////pAoAAAAAAAAEAAAASgAAAPz/////////rAoAAAAAAAAEAAAASwAAAPz/////////5AoAAAAAAAAEAAAATQAAAPz/////////7goAAAAAAAACAAAAQgAAAPz/////////FAsAAAAAAAAEAAAATQAAAPz/////////HgsAAAAAAAACAAAAQgAAAPz/////////SwsAAAAAAAACAAAAGQAAAPz/////////UgsAAAAAAAACAAAASAAAAPz/////////XAsAAAAAAAAEAAAASQAAAPz/////////YwsAAAAAAAACAAAASAAAAPz/////////jQsAAAAAAAACAAAASAAAAPz/////////kgsAAAAAAAAEAAAASgAAAPz/////////mgsAAAAAAAAEAAAASwAAAPz/////////vgsAAAAAAAAEAAAAWQAAAPz/////////1gsAAAAAAAAEAAAATAAAAPz/////////4gsAAAAAAAACAAAALQAAAPz/////////7gsAAAAAAAACAAAASAAAAPz/////////8wsAAAAAAAAEAAAASQAAAPz/////////+gsAAAAAAAACAAAASAAAAPz/////////FAwAAAAAAAAEAAAATwAAAPz/////////JAwAAAAAAAAEAAAATQAAAPz/////////LwwAAAAAAAACAAAAQgAAAPz/////////WwwAAAAAAAACAAAAHwAAAPz/////////YgwAAAAAAAACAAAASAAAAPz/////////bAwAAAAAAAAEAAAASQAAAPz/////////cwwAAAAAAAACAAAASAAAAPz/////////mQwAAAAAAAACAAAASAAAAPz/////////ngwAAAAAAAAEAAAASgAAAPz/////////pgwAAAAAAAAEAAAASwAAAPz/////////uQwAAAAAAAAEAAAAUAAAAPz/////////yQwAAAAAAAACAAAALgAAAPz/////////5wwAAAAAAAACAAAALwAAAPz/////////7gwAAAAAAAACAAAASAAAAPz/////////+AwAAAAAAAAEAAAASQAAAPz/////////Aw0AAAAAAAACAAAASAAAAPz/////////CA0AAAAAAAAEAAAAUQAAAPz/////////Dw0AAAAAAAACAAAAHAAAAPz/////////Hw0AAAAAAAAEAAAASQAAAPz/////////Lg0AAAAAAAAEAAAAUQAAAPz/////////Xw0AAAAAAAAEAAAASgAAAPz/////////Zw0AAAAAAAAEAAAASwAAAPz/////////uQ0AAAAAAAAEAAAAWgAAAPz/////////yQ0AAAAAAAAEAAAAWwAAAPz/////////3g0AAAAAAAAEAAAAWQAAAPz/////////9g0AAAAAAAAEAAAATAAAAPz/////////Cw4AAAAAAAACAAAAMAAAAPz/////////HA4AAAAAAAAEAAAATQAAAPz/////////Jw4AAAAAAAACAAAAQgAAAPz/////////VA4AAAAAAAAEAAAATQAAAPz/////////Xw4AAAAAAAACAAAAQgAAAPz/////////mQ4AAAAAAAACAAAAMQAAAPz/////////oA4AAAAAAAACAAAASAAAAPz/////////qg4AAAAAAAAEAAAASQAAAPz/////////tg4AAAAAAAACAAAASAAAAPz/////////uw4AAAAAAAAEAAAAUQAAAPz/////////wg4AAAAAAAACAAAAIQAAAPz/////////0g4AAAAAAAAEAAAASQAAAPz/////////3w4AAAAAAAAEAAAAUQAAAPz/////////5g4AAAAAAAACAAAAIQAAAPz/////////9g4AAAAAAAAEAAAASQAAAPz/////////Aw8AAAAAAAAEAAAAUQAAAPz/////////Cg8AAAAAAAACAAAAIQAAAPz/////////Gg8AAAAAAAAEAAAASQAAAPz/////////Jw8AAAAAAAAEAAAAUQAAAPz/////////Xw8AAAAAAAACAAAAJAAAAPz/////////Zg8AAAAAAAACAAAASAAAAPz/////////cA8AAAAAAAAEAAAASQAAAPz/////////dw8AAAAAAAACAAAASAAAAPz/////////oQ8AAAAAAAACAAAASAAAAPz/////////pg8AAAAAAAAEAAAASgAAAPz/////////rg8AAAAAAAAEAAAASwAAAPz/////////tQ8AAAAAAAAEAAAATgAAAPz/////////xA8AAAAAAAAEAAAATQAAAPz/////////zw8AAAAAAAACAAAAQgAAAPz/////////+w8AAAAAAAACAAAAIgAAAPz/////////AhAAAAAAAAACAAAASAAAAPz/////////DBAAAAAAAAAEAAAASQAAAPz/////////ExAAAAAAAAACAAAASAAAAPz/////////ORAAAAAAAAACAAAASAAAAPz/////////QRAAAAAAAAAEAAAASgAAAPz/////////SRAAAAAAAAAEAAAASwAAAPz/////////VhAAAAAAAAAEAAAATQAAAPz/////////YRAAAAAAAAACAAAAQgAAAPz/////////jBAAAAAAAAAEAAAATQAAAPz/////////qBAAAAAAAAAEAAAATQAAAPz/////////wRAAAAAAAAAEAAAAUgAAAPz/////////AQAAAAAAAAAEAAAARQAAAPz/////////MAAAAAAAAAAEAAAAWgAAAPz/////////rAAAAAAAAAAEAAAAXgAAAPz/////////vAAAAAAAAAAEAAAAXwAAAPz/////////xAAAAAAAAAAEAAAAYAAAAPz/////////yQAAAAAAAAAEAAAAUgAAAPz/////////IAAAAAAAAAAEAAAARQAAAPz/////////ZQAAAAAAAAAEAAAAYwAAAPz/////////fgAAAAAAAAAEAAAAZAAAAPz/////////iwAAAAAAAAACAAAAMgAAAPz/////////kAAAAAAAAAAEAAAAZQAAAPz/////////GAAAAAAAAAAEAAAARQAAAPz/////////NgAAAAAAAAAEAAAAaAAAAPz/////////EAAAAAAAAAACAAAAMwAAAPz/////////aQAAAAAAAAAEAAAAagAAAPz/////////hgAAAAAAAAAEAAAAawAAAPz/////////tQAAAAAAAAACAAAAZgAAAPz/////////vAAAAAAAAAACAAAANAAAAPz/////////xAAAAAAAAAACAAAAZwAAAPz/////////4wAAAAAAAAACAAAARgAAAPz/////////7AAAAAAAAAACAAAANQAAAPz/////////9AAAAAAAAAACAAAAZwAAAPz/////////EwEAAAAAAAACAAAAUwAAAPz/////////HQEAAAAAAAAEAAAATgAAAPz/////////MAEAAAAAAAAEAAAAbAAAAPz/////////ZgEAAAAAAAACAAAANgAAAPz/////////awEAAAAAAAACAAAAQwAAAPz/////////cgEAAAAAAAACAAAANgAAAPz/////////eQEAAAAAAAACAAAAbQAAAPz/////////gQEAAAAAAAAEAAAASQAAAPz/////////jQEAAAAAAAAEAAAAbgAAAPz/////////lAEAAAAAAAACAAAAbQAAAPz/////////nAEAAAAAAAAEAAAAbwAAAPz/////////pAEAAAAAAAAEAAAAcAAAAPz/////////rQEAAAAAAAACAAAANwAAAPz/////////twEAAAAAAAACAAAAQwAAAPz/////////vgEAAAAAAAACAAAANwAAAPz/////////xQEAAAAAAAACAAAAbQAAAPz/////////zQEAAAAAAAAEAAAASQAAAPz/////////1AEAAAAAAAACAAAAbQAAAPz/////////2QEAAAAAAAAEAAAAcAAAAPz/////////5QEAAAAAAAACAAAAOAAAAPz/////////6gEAAAAAAAACAAAAQwAAAPz/////////8QEAAAAAAAACAAAAOAAAAPz/////////+AEAAAAAAAACAAAASAAAAPz/////////AAIAAAAAAAAEAAAASQAAAPz/////////BwIAAAAAAAACAAAASAAAAPz/////////DAIAAAAAAAAEAAAAcAAAAPz/////////JgIAAAAAAAACAAAAZgAAAPz/////////MgIAAAAAAAAqAAAAcQAAAPz/////////OQIAAAAAAAACAAAAOQAAAPz/////////RgIAAAAAAAACAAAAXAAAAPz/////////YwIAAAAAAAAEAAAAbAAAAPz/////////gQIAAAAAAAACAAAAZgAAAPz/////////jQIAAAAAAAAqAAAAcQAAAPz/////////lAIAAAAAAAACAAAAOQAAAPz/////////oQIAAAAAAAACAAAAXAAAAPz/////////vgIAAAAAAAAEAAAAbAAAAPz/////////zAIAAAAAAAAEAAAAUgAAAPz/////////4gIAAAAAAAAEAAAAbAAAAPz/////////9QIAAAAAAAAEAAAAbAAAAPz//////////QIAAAAAAAAEAAAAXwAAAPz/////////EwMAAAAAAAACAAAABAAAAPz/////////HAMAAAAAAAAEAAAAcgAAAPz/////////IwMAAAAAAAAqAAAAcwAAAPz/////////KgMAAAAAAAACAAAAdAAAAPz/////////MQMAAAAAAAACAAAABAAAAPz/////////OgMAAAAAAAAEAAAAdQAAAPz/////////AAAAAAAAAAABAAAADgAAABADAAAAAAAAAAAAAAAAAAABAAAAYQAAAAAAAAAAAAAAIAAAAAAAAAACAAAABQAAAAAAAAAAAAAANAAAAAAAAAACAAAABgAAAAAAAAAAAAAASAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAiAAAAAAAAAACAAAAAgAAAJAIAAAAAAAA2wAAAAAAAAACAAAAXQAAAAAAAAAAAAAA8AAAAAAAAAACAAAACQAAAAAAAAAAAAAA+QAAAAAAAAACAAAACgAAAAAAAAAAAAAAQAEAAAAAAAACAAAADAAAAAAAAAAAAAAAfAEAAAAAAAACAAAADQAAAAAAAAAAAAAAyAEAAAAAAAACAAAADgAAAAAAAAAAAAAA0QEAAAAAAAACAAAADwAAAAAAAAAAAAAAHAIAAAAAAAACAAAADgAAABADAAAAAAAAAC5zeW10YWIALnN0cnRhYgAuc2hzdHJ0YWIALnJlbGEudGV4dAAuZGF0YQAuYnNzAC50ZXh0Ll9aTktTdDVjdHlwZUljRThkb193aWRlbkVjAC5yZWxhLnRleHQuX1pOU3QxMWNoYXJfdHJhaXRzSWNFNmxlbmd0aEVQS2MALnJvZGF0YS5zdHIxLjEALnJvZGF0YS5zdHIxLjgALnJlbGEudGV4dC5fWk45X19nbnVfY3h4Nl9fc3RvYUlsaWNKaUVFRVQwX1BGVF9QS1QxX1BQUzNfRHBUMl9FUEtjUzVfUG1TOV8ALmdjY19leGNlcHRfdGFibGUuX1pOOV9fZ251X2N4eDZfX3N0b2FJbGljSmlFRUVUMF9QRlRfUEtUMV9QUFMzX0RwVDJfRVBLY1M1X1BtUzlfAC5yb2RhdGEuX1pOU3Q3X19jeHgxMTEyYmFzaWNfc3RyaW5nSWNTdDExY2hhcl90cmFpdHNJY0VTYUljRUVDMkVQS2NSS1MzXy5zdHIxLjgALnJlbGEudGV4dC5fWk5TdDdfX2N4eDExMTJiYXNpY19zdHJpbmdJY1N0MTFjaGFyX3RyYWl0c0ljRVNhSWNFRUMyRVBLY1JLUzNfAC5yZWxhLnRleHQuX1pOS1N0N19fY3h4MTExMmJhc2ljX3N0cmluZ0ljU3QxMWNoYXJfdHJhaXRzSWNFU2FJY0VFN2NvbXBhcmVFUEtjAC5yZWxhLnRleHQuc3RhcnR1cAAuZ2NjX2V4Y2VwdF90YWJsZQAucmVsYS5pbml0X2FycmF5AC5yZWxhLmRhdGEucmVsLmxvY2FsLkRXLnJlZi5fX2d4eF9wZXJzb25hbGl0eV92MAAuY29tbWVudAAubm90ZS5HTlUtc3RhY2sALnJlbGEuZWhfZnJhbWUALmdyb3VwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsgIAABEAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAIAAAAAAAAACMAAABCAAAABAAAAAAAAAAEAAAAAAAAALICAAARAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAADAAAAAAAAAAjAAAAQwAAAAQAAAAAAAAABAAAAAAAAACyAgAAEQAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAABAAAAAAAAAAIwAAAFwAAAAEAAAAAAAAAAQAAAAAAAAAsgIAABEAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAAAAAAAMAAAAAAAAACMAAAA6AAAABAAAAAAAAAAEAAAAAAAAALICAAARAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAADAAAAAAAAAAjAAAAZwAAAAQAAAAAAAAABAAAAAAAAACyAgAAEQAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAwAAAAAAAAAIwAAAF0AAAAEAAAAAAAAAAQAAAAAAAAAIAAAAAEAAAAGAAAAAAAAAAAAAAAAAAAAkAAAAAAAAADFEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABsAAAAEAAAAQAAAAAAAAAAAAAAAAAAAAJAtAAAAAAAAgBYAAAAAAAAjAAAABwAAAAgAAAAAAAAAGAAAAAAAAAAmAAAAAQAAAAMAAAAAAAAAAAAAAAAAAABVEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAALAAAAAgAAAADAAAAAAAAAAAAAAAAAAAAVREAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADEAAAABAAAABgIAAAAAAAAAAAAAAAAAAGARAAAAAAAAAwAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABXAAAAAQAAAAYCAAAAAAAAAAAAAAAAAABwEQAAAAAAAAUAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAUgAAAAQAAABAAgAAAAAAAAAAAAAAAAAAEEQAAAAAAAAYAAAAAAAAACMAAAAMAAAACAAAAAAAAAAYAAAAAAAAAH4AAAABAAAAMgAAAAAAAAAAAAAAAAAAAHURAAAAAAAA0AEAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAACNAAAAAQAAADIAAAAAAAAAAAAAAAAAAABIEwAAAAAAAGMBAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAEAAAAAAAAAoQAAAAEAAAAGAgAAAAAAAAAAAAAAAAAAsBQAAAAAAADNAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAJwAAAAEAAAAQAIAAAAAAAAAAAAAAAAAAChEAAAAAAAAeAAAAAAAAAAjAAAAEAAAAAgAAAAAAAAAGAAAAAAAAADnAAAAAQAAAAICAAAAAAAAAAAAAAAAAAB9FQAAAAAAABQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAOQEAAAEAAAAyAAAAAAAAAAAAAAAAAAAAmBUAAAAAAAAqAAAAAAAAAAAAAAAAAAAACAAAAAAAAAABAAAAAAAAAI4BAAABAAAABgIAAAAAAAAAAAAAAAAAANAVAAAAAAAAlAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAACJAQAABAAAAEACAAAAAAAAAAAAAAAAAACgRAAAAAAAAHgAAAAAAAAAIwAAABQAAAAIAAAAAAAAABgAAAAAAAAA2gEAAAEAAAAGAgAAAAAAAAAAAAAAAAAAcBYAAAAAAAB5AAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAANUBAAAEAAAAQAIAAAAAAAAAAAAAAAAAABhFAAAAAAAAMAAAAAAAAAAjAAAAFgAAAAgAAAAAAAAAGAAAAAAAAAAoAgAAAQAAAAYAAAAAAAAAAAAAAAAAAADwFgAAAAAAAD4DAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAIwIAAAQAAABAAAAAAAAAAAAAAAAAAAAASEUAAAAAAAAoBQAAAAAAACMAAAAYAAAACAAAAAAAAAAYAAAAAAAAADYCAAABAAAAAgAAAAAAAAAAAAAAAAAAAC4aAAAAAAAAMQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABNAgAADgAAAAMAAAAAAAAAAAAAAAAAAABgGgAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAASAIAAAQAAABAAAAAAAAAAAAAAAAAAAAAcEoAAAAAAAAYAAAAAAAAACMAAAAbAAAACAAAAAAAAAAYAAAAAAAAAF4CAAABAAAAAwIAAAAAAAAAAAAAAAAAAGgaAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABZAgAABAAAAEACAAAAAAAAAAAAAAAAAACISgAAAAAAABgAAAAAAAAAIwAAAB0AAAAIAAAAAAAAABgAAAAAAAAAigIAAAEAAAAwAAAAAAAAAAAAAAAAAAAAcBoAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAJMCAAABAAAAAAAAAAAAAAAAAAAAAAAAAJoaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACoAgAAAQAAAAIAAAAAAAAAAAAAAAAAAACgGgAAAAAAADACAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAowIAAAQAAABAAAAAAAAAAAAAAAAAAAAAoEoAAAAAAAAgAQAAAAAAACMAAAAhAAAACAAAAAAAAAAYAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAANAcAAAAAAAAEAsAAAAAAAAkAAAAQgAAAAgAAAAAAAAAGAAAAAAAAAAJAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADgJwAAAAAAAKwFAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAEQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAwEsAAAAAAAC5AgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA=='


class Lab2TestClient(unittest.TestCase):

  def setUp(self):
    """
    Compile the program before testing
    """
    subprocess.check_call(["make", "lab2"])

    with open("lab2-ref.o", "wb") as f:
      f.write(base64.b64decode(REF_SOLUTION))
      
    subprocess.check_call(["g++", "lab2-ref.o", "-o", "lab2-ref.out"])
       

  def run_programs(self, delay):

    p = subprocess.Popen(["./lab2-ref.out", "server", f"{delay}"], stdout=subprocess.PIPE, text=True)
    r = subprocess.run(["./lab2.out", "client"], timeout=TIMEOUT)
    try:
      p.wait(timeout=TIMEOUT)
    except:
      p.terminate()
    
    return [l.strip() for l in p.stdout.readlines()]

  
  def test_connection(self):

    delay = random.randint(10, 19)

    user_result = self.run_programs(delay)

    self.assertIn("ACCEPTED", user_result)

  
  def test_discovery(self):

    delay = random.randint(10, 19)

    user_result = self.run_programs(delay)

    self.assertIn("DISCOVERY: OK", user_result)

  
  def test_request(self):

    delay = random.randint(10, 19)

    user_result = self.run_programs(delay)

    self.assertIn("REQUEST: OK", user_result)


  def test_resultfile(self):
    delay = random.randint(10, 19)

    self.run_programs(delay)

    with open("result-client.txt") as f:
      datalines = f.readlines()

    user_delay, user_ip = datalines[0].strip().split()

    user_delay = int(user_delay)

    self.assertLess(abs(delay * 1000 - user_delay), 2000)
    self.assertEqual(f"10.0.0.{delay}", user_ip)


class Lab2TestServer(unittest.TestCase):

  def setUp(self):
    """
    Compile the program before testing
    """
    subprocess.check_call(["make", "lab2"])

    with open("lab2-ref.o", "wb") as f:
      f.write(base64.b64decode(REF_SOLUTION))
      
    subprocess.check_call(["g++", "lab2-ref.o", "-o", "lab2-ref.out"])
       

  def run_programs(self, tid):

    p = subprocess.Popen(["./lab2.out", "server"])
    r = subprocess.run(["./lab2-ref.out", "client", f"{tid}"], timeout=TIMEOUT, stdout=subprocess.PIPE, text=True)
    try:
      p.wait(timeout=TIMEOUT)
    except:
      p.terminate()
    
    return [l.strip() for l in r.stdout.split("\n")]

  
  def test_connection(self):

    tid = random.randint(100, 199)

    user_result = self.run_programs(tid)

    self.assertIn("CONNECTED", user_result)

  
  def test_discovery(self):

    tid = random.randint(100, 199)

    user_result = self.run_programs(tid)

    self.assertIn("OFFER: OK", user_result)

  
  def test_request(self):

    tid = random.randint(100, 199)

    user_result = self.run_programs(tid)

    self.assertIn("ACKNOWLEDGE: OK", user_result)


  def test_resultfile(self):
    tid = random.randint(100, 199)

    self.run_programs(tid)

    with open("result-server.txt") as f:
      datalines = f.readlines()

    user_tid, user_ip = datalines[0].strip().split()

    user_tid = int(user_tid)

    self.assertEqual(tid, user_tid)

  
if __name__ == '__main__':

  suite = unittest.TestSuite()

  if len(sys.argv) == 2 and sys.argv[1] == "test-client":
    
    suite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(Lab2TestClient))


  elif len(sys.argv) == 2 and sys.argv[1] == "test-server":
    
    suite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(Lab2TestServer))


  elif len(sys.argv) == 2 and sys.argv[1] == "test-all":

    suite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(Lab2TestClient))
    suite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(Lab2TestServer))


  else:
    print("No tests requested")
    sys.exit(1)


  result = unittest.TextTestRunner().run(suite)

  # Set the exit code based on the test result
  sys.exit(not result.wasSuccessful())